const getEmployees = async () => {
    try {
        const res = await GetEmployees();
        return res;
    } catch(error) {
        console.log("ðŸš€ ~ getEmployees ~ error:", error);
        throw error;
    }
}

const deleteEmployee = async id => {
    try {
        const res = await DeleteEmployee(id);
        return res;
    } catch(error) {
        console.log("ðŸš€ ~ deleteEmployee ~ error:", error);
        throw error;
    }
}

const addEmployees = async (data) => {
    try {
        const res = await AddEmployees(data);
        return res;
    } catch(error) {
        console.log("ðŸš€ ~ addEmployees ~ error:", error);
        throw error;
    }
}

const getCompanies = async () => {
    try {
        const res = await GetCompanies();
        return res;
    } catch (error){
        console.log("ðŸš€ ~ getCompanies ~ error:", error);
        throw error;
    }
}